// Gestione della lingua (Italiano / Inglese)
const translations = {
    it: {
        "nav.about": "CHI SONO",
        "nav.projects": "I MIEI LAVORI",
        "nav.experiences": "LE MIE ESPERIENZE",
        
        "hero.title": "Ciao, mi chiamo <strong>Marco.</strong>",
        "hero.subtitle_prefix": "Sono ",
        "typing.words": ["uno studente.", "curioso.", "appassionato di informatica."],
        
        "about.heading": "Chi sono.",
        "about.p1": "Mi chiamo <strong>Marco</strong>, ho <strong>16 anni</strong> e frequento il terzo anno di un Istituto Tecnico Industriale ad indirizzo Informatica e Telecomunicazioni.",
        "about.p2": "Online uso spesso il nickname <strong>justMarcolin</strong>.",
        "about.p3": "Mi appassionano la <strong>programmazione</strong>, la <strong>tecnologia</strong> e tutto ciò che riguarda il mondo dell’ <strong><u>informatica</u></strong>.",
        "about.p4": "Nel tempo libero sperimento con nuovi linguaggi, lavoro su piccoli progetti personali e approfondisco ciò che studio a scuola.",
        "about.p5": "Mi piace mettermi alla prova, imparare cose nuove e migliorare costantemente le mie competenze.",
        "about.p6": "Di recente ho creato <strong>jLabs</strong>, un mio piccolo \"brand personale\" che ha dato vita a <strong><u>purpleGPT</u></strong>, la mia ultima produzione.",
        
        "projects.heading": "I miei lavori.",
        "projects.purplegpt.desc": "Una IA che si integra al tuo server Discord, un progetto <a href=\"https://www.youtube.com/@jlabs-team/\">jLabs</a>.",
        "projects.greendevelopbot.desc": "Un bot Discord multi-purpose scritto in Python usando la libreria <a href=\"https://discordpy.readthedocs.io/en/stable/\">Discord.py</a>.",
        "projects.bashtard.desc": "Un terminale... non molto amichevole! Risposte sarcastiche generate da un modello di AI locale.",
        
        "experiences.heading": "Le mie esperienze.",
        "experiences.rabbit.title": "Android su Rabbit R1",
        "experiences.rabbit.desc": "Ho installato Android 13 su un Rabbit R1 usando <a href=\"https://github.com/RabbitHoleEscapeR1/r1_escape\">r1_escape</a>.",
        "experiences.homelab.title": "Homelabbing",
        "experiences.homelab.desc": "Ho fatto esperienze di homelabbing usando <a href=\"https://www.proxmox.com/en/products/proxmox-virtual-environment/overview\">Proxmox VE</a> e <a href=\"https://learn.microsoft.com/it-it/windows-server/virtualization/hyper-v/overview\">Hyper-V.</a>",
        "experiences.vm.title": "Macchine Virtuali",
        "experiences.vm.desc": "Uso quotidianamente VM per testare nuovi software e sistemi operativi.",
        
        "footer.text": "© 2026 <a href=\"/\">justmarcolin.dev</a> | Tutti i diritti riservati"
    },
    en: {
        "nav.about": "ABOUT ME",
        "nav.projects": "MY WORKS",
        "nav.experiences": "MY EXPERIENCES",
        
        "hero.title": "Hi, my name is <strong>Marco.</strong>",
        "hero.subtitle_prefix": "I am ",
        "typing.words": ["a student.", "curious.", "passionate about IT."],
        
        "about.heading": "About me.",
        "about.p1": "My name is <strong>Marco</strong>, I am <strong>16 years old</strong> and I attend the third year of an IT & Telecommunications High School.",
        "about.p2": "Online I often use the nickname <strong>justMarcolin</strong>.",
        "about.p3": "I am passionate about <strong>programming</strong>, <strong>technology</strong> and everything related to <strong><u>computer science</u></strong>.",
        "about.p4": "In my free time I experiment with new languages, work on small personal projects and deepen what I study at school.",
        "about.p5": "I like to challenge myself, learn new things and constantly improve my skills.",
        "about.p6": "Recently I created <strong>jLabs</strong>, my small \"personal brand\" that brought <strong><u>purpleGPT</u></strong> to life, my latest creation.",
        
        "projects.heading": "My works.",
        "projects.purplegpt.desc": "An AI that integrates into your Discord server, a <a href=\"https://www.youtube.com/@jlabs-team/\">jLabs</a> project.",
        "projects.greendevelopbot.desc": "A multi-purpose Discord bot written in Python using the <a href=\"https://discordpy.readthedocs.io/en/stable/\">Discord.py</a> library.",
        "projects.bashtard.desc": "A terminal... not very friendly! Sarcastic responses generated by a local AI model.",
        
        "experiences.heading": "My experiences.",
        "experiences.rabbit.title": "Android on Rabbit R1",
        "experiences.rabbit.desc": "I installed Android 13 on a Rabbit R1 using <a href=\"https://github.com/RabbitHoleEscapeR1/r1_escape\">r1_escape</a>.",
        "experiences.homelab.title": "Homelabbing",
        "experiences.homelab.desc": "I gained homelabbing experience using <a href=\"https://www.proxmox.com/en/products/proxmox-virtual-environment/overview\">Proxmox VE</a> and <a href=\"https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/overview\">Hyper-V.</a>",
        "experiences.vm.title": "Virtual Machines",
        "experiences.vm.desc": "I use VMs daily to test new software and operating systems.",
        
        "footer.text": "© 2026 <a href=\"/\">justmarcolin.dev</a> | All Rights Reserved"
    }
};

function setLanguage(lang) {
    if (!translations[lang]) lang = 'it';
    localStorage.setItem('preferred_lang', lang);
    const select = document.getElementById('langSelect');
    if (select) select.value = lang;
    document.documentElement.lang = lang;

    const t = translations[lang];
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (t[key] !== undefined) {
            el.innerHTML = t[key];
        }
    });

    if (window.updateTypingWords) {
        window.updateTypingWords(t["typing.words"]);
    }
}

function changeLanguage() {
    const select = document.getElementById('langSelect');
    if (select) {
        setLanguage(select.value);
    }
}

function detectDefaultLanguage() {
    const savedLang = localStorage.getItem('preferred_lang');
    if (savedLang && translations[savedLang]) {
        return savedLang;
    }
    const browserLang = (navigator.language || navigator.userLanguage || '').toLowerCase();
    if (browserLang.startsWith('it')) {
        return 'it';
    }
    return 'en';
}

document.addEventListener('DOMContentLoaded', () => {
    const initialLang = detectDefaultLanguage();
    setLanguage(initialLang);
});
